- name: Build project
        run: |
          echo "=== ANTES DO BUILD ==="
          pwd
          ls -la
          echo "=== PACKAGE.JSON SCRIPTS ==="
          cat package.json | grep -A 10 '"scripts"'
          echo "=== EXECUTANDO BUILD ==="
          npm run build
          echo "=== DEPOIS DO BUILD ==="
          ls -la
          echo "=== VERIFICANDO DIST ==="
          if [ -d "dist" ]; then
            echo "✅ Pasta dist encontrada!"
            echo "Conteúdo da dist:"
            ls -la dist/
            echo "Arquivos na dist:"
            find dist/ -type f
          else
            echo "❌ ERRO: Pasta dist NÃO foi criada!"
            echo "Verificando outras pastas possíveis:"
            ls -la build/ 2>/dev/null || echo "Pasta build não existe"
            ls -la out/ 2>/dev/null || echo "Pasta out não existe"
            ls -la public/ 2>/dev/null && echo "Conteúdo public:" && ls -la public/
          fi
          echo "=== VERIFICANDO VITE CONFIG ==="
          if [ -f "vite.config.ts" ]; then
            echo "vite.config.ts existe:"
            cat vite.config.ts | head -20
          fi
